export const actionTypes = {
        FETCH_STARTED: "FETCH_STARTED",
        FETCH_SUCCESS: "FETCH_SUCCESS",
        FETCH_FAILED: "FETCH_FAILED",
        SWITCH_PAGE: "SWITCH_PAGE",
        SWITCH_COLOR: "SWITCH_COLOR",
        SET_FILTER: "SET_FILTER"
}